const projects = [
    {
        id: "1",
        imgSrc: "./ProjectAssets/1.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-E-Commerce-React-Redux-N.git",
        projectSrc: "https://pp-e-commerce-react-redux.netlify.app/",
        title: "E-com (use Redux)",
        category: "React JS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "2",
        imgSrc: "./ProjectAssets/2.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-ChatAPP-APPWrite-N.git",
        projectSrc: "https://pp-chatapp-appwrite.netlify.app/",
        title: "Chat Application",
        category: "MERN Stack",
        level: "Advance",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "3",
        imgSrc: "./ProjectAssets/3.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Todo-With-Context-API-N.git",
        projectSrc: "https://pp-todo-with-context-api.netlify.app/",
        title: "Todo App (Context API)",
        category: "React JS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "4",
        imgSrc: "./ProjectAssets/4.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Advanced-Routing-Web-N.git",
        projectSrc: "https://pp-advanced-routing-web.netlify.app/",
        title: "Full Web App",
        category: "React JS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "5",
        imgSrc: "./ProjectAssets/5.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Password-Generator-N.git",
        projectSrc: "https://pp-password-generator.netlify.app/",
        title: "Password Generator",
        category: "Javascript",
        level: "Basic",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "6",
        imgSrc: "./ProjectAssets/6.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PPB-MERN-Crud-Operation-CSH.git",
        projectSrc: "https://ppf-mern-crud-operation.netlify.app/",
        title: "MERN CRUD project",
        category: "MERN Stack",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "7",
        imgSrc: "./ProjectAssets/7.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Todo-App-Local-Storage-N.git",
        projectSrc: "https://pp-todo-app-local-storage.netlify.app/",
        title: "Todo App",
        category: "React JS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "8",
        imgSrc: "./ProjectAssets/8.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-MKl-Skills-Zone-Tailwind-N.git",
        projectSrc: "https://pp-mkl-skills-zone-tailwind.netlify.app/",
        title: "MKL Skills Zone",
        category: "Tailwind CSS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "9",
        imgSrc: "./ProjectAssets/9.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Simple-Crud-Operation-Mock-Api-N.git",
        projectSrc: "https://pp-simple-crud-operation-mock-api.netlify.app/",
        title: "Crud using Mock Api",
        category: "React JS",
        level: "Basic",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "10",
        imgSrc: "./ProjectAssets/10.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Simple-Landing-Page-Tailwind-N.git",
        projectSrc: "https://pp-simple-landing-page-tailwind.netlify.app/",
        title: "Descent Landing Page",
        category: "Tailwind CSS",
        level: "Basic",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "11",
        imgSrc: "./ProjectAssets/11.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Canvas-Powerfull-Animation-N.git",
        projectSrc: "https://pp-canvas-powerfull-animation.netlify.app/",
        title: "Canvas Animation",
        category: "Javascript",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "12",
        imgSrc: "./ProjectAssets/12.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Text-Editor-N.git",
        projectSrc: "https://pp-text-editor.netlify.app/",
        title: "MKL Text Editor",
        category: "React JS",
        level: "Advance",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "13",
        imgSrc: "./ProjectAssets/13.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Too-Goods-N.git",
        projectSrc: "https://pp-too-goods.netlify.app/",
        title: "Too Goods",
        category: "Javascript",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "14",
        imgSrc: "./ProjectAssets/14.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Bubble-Game-N.git",
        projectSrc: "https://pp-bubble-game.netlify.app/",
        title: "Bubble Game",
        category: "Javascript",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "15",
        imgSrc: "./ProjectAssets/15.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Quotes-Generator-N.git",
        projectSrc: "https://pp-quotes-generator.netlify.app/",
        title: "Quotes Generator",
        category: "Javascript",
        level: "Basic",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "16",
        imgSrc: "./ProjectAssets/16.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Animated-Landing-Page-N.git",
        projectSrc: "https://pp-animated-landing-page.netlify.app/",
        title: "Animated Landing Page",
        category: "CSS",
        level: "Intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "17",
        imgSrc: "./ProjectAssets/17.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Simple-Landing-Page-N.git",
        projectSrc: "https://pp-simple-landing-page.netlify.app/",
        title: "Simple Landing Page",
        category: "CSS",
        level: "Basic",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
]

export default projects;