const projects = [
    {
        id: "1",
        imgSrc: "./ProjectAssets/1.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-E-Commerce-React-Redux-N.git",
        projectSrc: "https://pp-e-commerce-react-redux.netlify.app/",
        title: "E-com (use Redux)",
        category: "React JS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "2",
        imgSrc: "./ProjectAssets/2.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-ChatAPP-APPWrite-N.git",
        projectSrc: "https://pp-chatapp-appwrite.netlify.app/",
        title: "Chat Application",
        category: "MERN Stack",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "3",
        imgSrc: "./ProjectAssets/3.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Todo-With-Context-API-N.git",
        projectSrc: "https://pp-todo-with-context-api.netlify.app/",
        title: "Todo App (Context API)",
        category: "React JS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "4",
        imgSrc: "./ProjectAssets/4.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Advanced-Routing-Web-N.git",
        projectSrc: "https://pp-advanced-routing-web.netlify.app/",
        title: "Full Web App",
        category: "React JS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "5",
        imgSrc: "./ProjectAssets/5.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Password-Generator-N.git",
        projectSrc: "https://pp-password-generator.netlify.app/",
        title: "Password Generator",
        category: "Javascript",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "6",
        imgSrc: "./ProjectAssets/6.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PPB-MERN-Crud-Operation-CSH.git",
        projectSrc: "https://ppf-mern-crud-operation.netlify.app/",
        title: "MERN CRUD project",
        category: "MERN Stack",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "7",
        imgSrc: "./ProjectAssets/7.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Todo-App-Local-Storage-N.git",
        projectSrc: "https://pp-todo-app-local-storage.netlify.app/",
        title: "Todo App (localstorage)",
        category: "React JS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "8",
        imgSrc: "./ProjectAssets/8.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-MKl-Skills-Zone-Tailwind-N.git",
        projectSrc: "https://pp-mkl-skills-zone-tailwind.netlify.app/",
        title: "MKL Skills Zone (Tailwind)",
        category: "Tailwind CSS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "9",
        imgSrc: "./ProjectAssets/9.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Simple-Crud-Operation-Mock-Api-N.git",
        projectSrc: "https://pp-simple-crud-operation-mock-api.netlify.app/",
        title: "Crud using Mock Api",
        category: "React JS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
    {
        id: "10",
        imgSrc: "./ProjectAssets/10.png",
        gitHubSrc: "https://github.com/ManasKumarLal/PP-Simple-Landing-Page-Tailwind-N.git",
        projectSrc: "https://pp-simple-landing-page-tailwind.netlify.app/",
        title: "Descent Landing Page",
        category: "Tailwind CSS",
        level: "intermediate",
        skills: "flex box, grid, transformation, and other important css properties",
        persons: "Team",
    },
]

export default projects;